/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsExecutiveRouteImport } from './routes/rooms.executive'
import { Route as RoomsStandardRouteImport } from './routes/rooms.standard'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminBookingsIdRouteImport } from './routes/admin.bookings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsExecutiveRoute = RoomsExecutiveRouteImport.update({
  id: '/rooms/executive',
  path: '/rooms/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsStandardRoute = RoomsStandardRouteImport.update({
  id: '/rooms/standard',
  path: '/rooms/standard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/rooms/executive': typeof RoomsExecutiveRoute
  '/rooms/standard': typeof RoomsStandardRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/rooms/executive': typeof RoomsExecutiveRoute
  '/rooms/standard': typeof RoomsStandardRoute
  '/admin': typeof AdminIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/gallery': typeof GalleryRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/rooms/executive': typeof RoomsExecutiveRoute
  '/rooms/standard': typeof RoomsStandardRoute
  '/admin/': typeof AdminIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/admin/calendar'
    | '/admin/gallery'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/login'
    | '/rooms/executive'
    | '/rooms/standard'
    | '/admin/'
    | '/rooms/'
    | '/admin/bookings/$id'
    | '/admin/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/admin/calendar'
    | '/admin/gallery'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/login'
    | '/rooms/executive'
    | '/rooms/standard'
    | '/admin'
    | '/rooms'
    | '/admin/bookings/$id'
    | '/admin/bookings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/experience'
    | '/gallery'
    | '/admin/calendar'
    | '/admin/gallery'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin_/login'
    | '/rooms/executive'
    | '/rooms/standard'
    | '/admin/'
    | '/rooms/'
    | '/admin/bookings/$id'
    | '/admin/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  GalleryRoute: typeof GalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  RoomsExecutiveRoute: typeof RoomsExecutiveRoute
  RoomsStandardRoute: typeof RoomsStandardRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/executive': {
      id: '/rooms/executive'
      path: '/rooms/executive'
      fullPath: '/rooms/executive'
      preLoaderRoute: typeof RoomsExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/standard': {
      id: '/rooms/standard'
      path: '/rooms/standard'
      fullPath: '/rooms/standard'
      preLoaderRoute: typeof RoomsStandardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  GalleryRoute: GalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  RoomsExecutiveRoute: RoomsExecutiveRoute,
  RoomsStandardRoute: RoomsStandardRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
